name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/1200 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "dunkverse@gmail.com"
          git config --local user.name "dunkverse"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "good good study day day up"
          git push
